#!/usr/bin/env bash
set -euo pipefail

if ! command -v opencode >/dev/null 2>&1; then
  echo "OpenCode is not installed or is not on PATH." >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required to resolve the current models safely." >&2
  exit 1
fi

TMP_RAW="$(mktemp)"
TMP_CLEAN="$(mktemp)"
trap 'rm -f "$TMP_RAW" "$TMP_CLEAN"' EXIT

# Refresh OpenCode's provider catalog instead of trusting stale model names.
if ! opencode models openrouter --refresh >"$TMP_RAW" 2>&1; then
  echo "Could not refresh OpenRouter models through OpenCode." >&2
  cat "$TMP_RAW" >&2
  exit 1
fi

# Strip ANSI escape sequences before parsing model IDs.
python3 - "$TMP_RAW" "$TMP_CLEAN" <<'PY'
import re
import sys
src, dst = sys.argv[1:3]
text = open(src, "r", encoding="utf-8", errors="replace").read()
text = re.sub(r"\x1b\[[0-?]*[ -/]*[@-~]", "", text)
open(dst, "w", encoding="utf-8").write(text)
PY

# Ox Alpha's stealth preview ended Aug 26, 2026. Keep the familiar `ai ox`
# shortcut, but when the retired stealth route is absent, resolve it to the
# revealed/current Z.AI GLM route instead of leaving a dead model ID.
OX_MODEL="$(python3 - "$TMP_CLEAN" <<'PY'
import re
import sys

text = open(sys.argv[1], "r", encoding="utf-8", errors="replace").read()
ids = sorted(set(re.findall(r"openrouter/[^\s]+", text)))

for preferred in (
    "openrouter/stealth/ox-alpha",
    "openrouter/z-ai/glm-5.3",
    "openrouter/z-ai/glm-latest",
):
    if preferred in ids:
        print(preferred)
        raise SystemExit(0)

def glm_version(model):
    m = re.search(r"glm[-_. ]?([0-9]+)(?:[.-]([0-9]+))?", model.lower())
    return (int(m.group(1)), int(m.group(2) or 0)) if m else (0, 0)

glm_ids = [m for m in ids if m.startswith("openrouter/z-ai/glm-")]
if glm_ids:
    print(max(glm_ids, key=lambda model: (glm_version(model), model)))
PY
)"
if [[ -z "$OX_MODEL" ]]; then
  OX_MODEL="openrouter/z-ai/glm-5.3"
  echo "Warning: neither Ox Alpha nor a current GLM route was found in the refreshed catalog; using fallback $OX_MODEL" >&2
fi

QWEN_MODEL="$(python3 - "$TMP_CLEAN" <<'PY'
import re
import sys

text = open(sys.argv[1], "r", encoding="utf-8", errors="replace").read()
ids = sorted(set(re.findall(r"openrouter/qwen/[^\s]+", text)))

def version(model):
    s = model.lower()
    m = re.search(r"qwen\s*([0-9]+)(?:[.\-_]?([0-9]+))?", s)
    return (int(m.group(1)), int(m.group(2) or 0)) if m else (0, 0)

def scale(model):
    s = model.lower()
    m = re.search(r"(?:^|[-_/])(\d+(?:\.\d+)?)t(?:[-_/]|$)", s)
    if m:
        return float(m.group(1)) * 1000.0
    m = re.search(r"(?:^|[-_/])(\d+(?:\.\d+)?)b(?:[-_/]|$)", s)
    return float(m.group(1)) if m else 0.0

if ids:
    print(max(ids, key=lambda model: (version(model), scale(model), model)))
PY
)"

if [[ -z "$QWEN_MODEL" ]]; then
  QWEN_MODEL="openrouter/qwen/qwen3.8-2.4t-a95b"
  echo "Warning: Qwen was not found in the refreshed OpenCode catalog; using current fallback $QWEN_MODEL" >&2
fi

INSTALL_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/nicholas-ai-switchboard"
LAUNCHER="$INSTALL_DIR/ai"
MODEL_FILE="$CONFIG_DIR/models.env"
mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"

cat >"$MODEL_FILE" <<EOF
# Generated by Nicholas-AI-OS/scripts/install_ai_switcher.sh
AI_OX_MODEL='$OX_MODEL'
AI_QWEN_MODEL='$QWEN_MODEL'
EOF
chmod 600 "$MODEL_FILE"

cat >"$LAUNCHER" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

MODEL_FILE="$HOME/.config/nicholas-ai-switchboard/models.env"
if [[ -f "$MODEL_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$MODEL_FILE"
fi

AI_OX_MODEL="${AI_OX_MODEL:-openrouter/z-ai/glm-5.3}"
AI_QWEN_MODEL="${AI_QWEN_MODEL:-openrouter/qwen/qwen3.8-2.4t-a95b}"

usage() {
  cat <<USAGE
Nicholas AI Switcher

  ai             Open OpenCode and use its built-in model selector
  ai ox          Open current project with the Ox successor/current GLM route
  ai qwen        Open current project with the verified Qwen model
  ai models      Refresh/show available OpenRouter models
  ai status      Show the model IDs currently assigned to shortcuts

Inside OpenCode you can also press Ctrl+X then M to switch models.
USAGE
}

case "${1:-}" in
  "")
    exec opencode "$PWD"
    ;;
  ox)
    exec opencode "$PWD" --model "$AI_OX_MODEL"
    ;;
  qwen)
    exec opencode "$PWD" --model "$AI_QWEN_MODEL"
    ;;
  models)
    exec opencode models openrouter --refresh
    ;;
  status)
    printf 'Ox/GLM: %s\nQwen:   %s\n' "$AI_OX_MODEL" "$AI_QWEN_MODEL"
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    echo "Unknown AI shortcut: $1" >&2
    usage >&2
    exit 2
    ;;
esac
EOF
chmod 700 "$LAUNCHER"

SHELL_RC=""
case "${SHELL##*/}" in
  zsh) SHELL_RC="$HOME/.zshrc" ;;
  bash) SHELL_RC="$HOME/.bashrc" ;;
esac

if [[ -n "$SHELL_RC" ]]; then
  touch "$SHELL_RC"
  if ! grep -Fq 'export PATH="$HOME/.local/bin:$PATH"' "$SHELL_RC"; then
    printf '\n# Nicholas AI Switcher\nexport PATH="$HOME/.local/bin:$PATH"\n' >>"$SHELL_RC"
  fi
fi

export PATH="$HOME/.local/bin:$PATH"

echo "AI switcher installed: $LAUNCHER"
echo "Verified Ox/GLM shortcut: $OX_MODEL"
echo "Verified Qwen shortcut:   $QWEN_MODEL"
echo
echo "Use: ai | ai ox | ai qwen | ai models | ai status"
